name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'coqorg/coq:dev'
          - 'coqorg/coq:8.14'
          - 'coqorg/coq:8.13'
          - 'coqorg/coq:8.12'
          - 'coqorg/coq:8.11'
          - 'coqorg/coq:8.10'
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'coq-googology.opam'
          custom_image: ${{ matrix.image }}
